version: "3.5"

services:
  postgres:
    container_name: postgres-db
    hostname: localhost
    image: postgres:16.2
    environment:
      POSTGRES_USER: dinhloc
      POSTGRES_PASSWORD: dinhloc
      POSTGRES_DB: elearning
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5555:5432"
volumes:
  postgres: