version: '3.5'
services:
  postgres:
    image: postgres:latest
    hostname: localhost
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db-elearning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: